<template>
  <div>
    <p>
      <vxe-breadcrumb>
        <vxe-breadcrumb-item>首页</vxe-breadcrumb-item>
        <vxe-breadcrumb-item>系统设置</vxe-breadcrumb-item>
        <vxe-breadcrumb-item>菜单设置</vxe-breadcrumb-item>
      </vxe-breadcrumb>
    </p>
  </div>
</template>
